### ISSUE TITLE
Fix CRISPR repeat naming scheme

### ISSUE THREAD

**Issue by ryneches** [ryneches/viralnet#11]
`all_repeats.fna` contains 16,001,811 records, but only 2,606,513 unique record identifiers. I *think* this is because repeats in the same array have all been assigned the same record identifier, which should be easy to fix.

**Comment by daviye** [comment]
yes, that's indeed the situation.
however, some repeat sequences are different even if they have the same identifier (due to the plasticity of repeats or an assembly error). Feel free to add an extra number to all unique entries (both identifier and sequence).
